// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitTest(a int) *BigConf {
	conf := CreateConf(a)
	bigConf := TestConf(conf)
	return bigConf
}
